# Generated by Django 3.0.5 on 2020-04-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='novoCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dataNasc', models.DateTimeField()),
            ],
        ),
    ]
